// ACTIONS CONSTANTS
export const GET_MANIFESTS = "GET_MANIFESTS";
export const SHOW_ERROR = "SHOW_ERROR";
export const UPDATE_FILTER_ROVER = "UPDATE_FILTER_ROVER";
export const UPDATE_FILTER_CAMERA = "UPDATE_FILTER_CAMERA";
export const UPDATE_FILTER_EARTH_DATE = "UPDATE_FILTER_EARTH_DATE";
export const UPDATE_FILTER_SOL_DATE = "UPDATE_FILTER_SOL_DATE";
export const UPDATE_PHOTOS = "UPDATE_PHOTOS";
export const UPDATE_MORE_PHOTOS = "UPDATE_MORE_PHOTOS";
export const LOADER_PHOTOS_ON = "LOADER_PHOTOS_ON";
export const LOADER_PHOTOS_OFF = "LOADER_PHOTOS_OFF";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const UPDATE_FILTERS_FROM_LOCAL_STORAGE =
  "UPDATE_FILTERS_FROM_LOCAL_STORAGE";
